import:
  - ~/.config/alacritty/fonts.yml
  - ~/.config/alacritty/themes/Nord.yml
  - ~/.config/alacritty/bindings.yml

env:
  TERM: xterm-256color

window:
  padding:
    x: 15
    y: 15

  dynamic_padding: false

  decorations: none

  startup_mode: Windowed

  title: Alacritty

  class:
    instance: Alacritty
    general: Alacritty

scrolling:
  history: 5000

visual_bell:
  animation: EaseOutExpo
  duration: 0.5
  color: "#ffffff"

background_opacity: 1.0

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

dynamic_title: true

cursor:
  style: Block

live_config_reload: true

shell:
  program: /bin/bash

