colors:
  name: Ashes (dark)
  author: Chris Kempson
  primary:
    background: "#1c2023"
    foreground: "#c7ccd1"
  cursor:
    text: "#1c2023"
    cursor: "#c7ccd1"
  normal:
    black: "#1c2023"
    red: "#c7ae95"
    green: "#95c7ae"
    yellow: "#aec795"
    blue: "#ae95c7"
    magenta: "#c795ae"
    cyan: "#95aec7"
    white: "#c7ccd1"
  bright:
    black: "#747c84"
    red: "#c7ae95"
    green: "#95c7ae"
    yellow: "#aec795"
    blue: "#ae95c7"
    magenta: "#c795ae"
    cyan: "#95aec7"
    white: "#f3f4f5"
