colors:
  name: astromouse
  author: ""
  primary:
    background: "#000000"
    foreground: "#ffffff"
  cursor:
    text: "#000000"
    cursor: "#ffffff"
  normal:
    black: "#1c1c1c"
    red: "#d770af"
    green: "#9acc79"
    yellow: "#d0d26b"
    blue: "#77b6c5"
    magenta: "#a488d9"
    cyan: "#7fcab3"
    white: "#8d8d8d"
  bright:
    black: "#3d3a3a"
    red: "#d28abf"
    green: "#8fb676"
    yellow: "#c8bc45"
    blue: "#8fa7b9"
    magenta: "#bd89de"
    cyan: "#6ec2a8"
    white: "#dad3d3"
