colors:
  name: Atelierseaside (light)
  author: Chris Kempson
  primary:
    background: "#f0fff0"
    foreground: "#5e6e5e"
  cursor:
    text: "#f0fff0"
    cursor: "#5e6e5e"
  normal:
    black: "#131513"
    red: "#e6193c"
    green: "#29a329"
    yellow: "#c3c322"
    blue: "#3d62f5"
    magenta: "#ad2bee"
    cyan: "#1999b3"
    white: "#8ca68c"
  bright:
    black: "#687d68"
    red: "#e6193c"
    green: "#29a329"
    yellow: "#c3c322"
    blue: "#3d62f5"
    magenta: "#ad2bee"
    cyan: "#1999b3"
    white: "#f0fff0"
