colors:
  name: Atelierforest (dark)
  author: Chris Kempson
  primary:
    background: "#1b1918"
    foreground: "#a8a19f"
  cursor:
    text: "#1b1918"
    cursor: "#a8a19f"
  normal:
    black: "#1b1918"
    red: "#f22c40"
    green: "#5ab738"
    yellow: "#d5911a"
    blue: "#407ee7"
    magenta: "#6666ea"
    cyan: "#00ad9c"
    white: "#a8a19f"
  bright:
    black: "#766e6b"
    red: "#f22c40"
    green: "#5ab738"
    yellow: "#d5911a"
    blue: "#407ee7"
    magenta: "#6666ea"
    cyan: "#00ad9c"
    white: "#f1efee"
