colors:
  name: Atelierheath (light)
  author: Chris Kempson
  primary:
    background: "#f7f3f7"
    foreground: "#695d69"
  cursor:
    text: "#f7f3f7"
    cursor: "#695d69"
  normal:
    black: "#1b181b"
    red: "#ca402b"
    green: "#379a37"
    yellow: "#bb8a35"
    blue: "#516aec"
    magenta: "#7b59c0"
    cyan: "#159393"
    white: "#ab9bab"
  bright:
    black: "#776977"
    red: "#ca402b"
    green: "#379a37"
    yellow: "#bb8a35"
    blue: "#516aec"
    magenta: "#7b59c0"
    cyan: "#159393"
    white: "#f7f3f7"
