colors:
  name: Atelierdune (light)
  author: Chris Kempson
  primary:
    background: "#fefbec"
    foreground: "#6e6b5e"
  cursor:
    text: "#fefbec"
    cursor: "#6e6b5e"
  normal:
    black: "#20201d"
    red: "#d73737"
    green: "#60ac39"
    yellow: "#cfb017"
    blue: "#6684e1"
    magenta: "#b854d4"
    cyan: "#1fad83"
    white: "#a6a28c"
  bright:
    black: "#7d7a68"
    red: "#d73737"
    green: "#60ac39"
    yellow: "#cfb017"
    blue: "#6684e1"
    magenta: "#b854d4"
    cyan: "#1fad83"
    white: "#fefbec"
