colors:
  name: Belge
  author: ""
  primary:
    background: "#000000"
    foreground: "#ffffff"
  cursor:
    text: "#000000"
    cursor: "#ffffff"
  normal:
    black: "#252525"
    red: "#ef6769"
    green: "#a6e22e"
    yellow: "#fd971f"
    blue: "#6495ed"
    magenta: "#deb887"
    cyan: "#b0c4de"
    white: "#dbdcdc"
  bright:
    black: "#454545"
    red: "#fc7ca5"
    green: "#b6e354"
    yellow: "#fd971f"
    blue: "#87ceeb"
    magenta: "#996600"
    cyan: "#87ceeb"
    white: "#fdfdfd"
