colors:
  name: Bitmute
  author: ""
  primary:
    background: "#000000"
    foreground: "#ffffff"
  cursor:
    text: "#000000"
    cursor: "#ffffff"
  normal:
    black: "#282828"
    red: "#b76969"
    green: "#719d72"
    yellow: "#909858"
    blue: "#68668f"
    magenta: "#966894"
    cyan: "#688891"
    white: "#8e8e8e"
  bright:
    black: "#494949"
    red: "#b87e7e"
    green: "#839d84"
    yellow: "#919864"
    blue: "#73718f"
    magenta: "#987397"
    cyan: "#758c93"
    white: "#aeaeae"
