colors:
  name: Brewer (light)
  author: Chris Kempson
  primary:
    background: "#fcfdfe"
    foreground: "#515253"
  cursor:
    text: "#fcfdfe"
    cursor: "#515253"
  normal:
    black: "#0c0d0e"
    red: "#e31a1c"
    green: "#31a354"
    yellow: "#dca060"
    blue: "#3182bd"
    magenta: "#756bb1"
    cyan: "#80b1d3"
    white: "#b7b8b9"
  bright:
    black: "#737475"
    red: "#e31a1c"
    green: "#31a354"
    yellow: "#dca060"
    blue: "#3182bd"
    magenta: "#756bb1"
    cyan: "#80b1d3"
    white: "#fcfdfe"
