colors:
  name: Chalk (dark)
  author: Chris Kempson
  primary:
    background: "#151515"
    foreground: "#d0d0d0"
  cursor:
    text: "#151515"
    cursor: "#d0d0d0"
  normal:
    black: "#151515"
    red: "#fb9fb1"
    green: "#acc267"
    yellow: "#ddb26f"
    blue: "#6fc2ef"
    magenta: "#e1a3ee"
    cyan: "#12cfc0"
    white: "#d0d0d0"
  bright:
    black: "#505050"
    red: "#fb9fb1"
    green: "#acc267"
    yellow: "#ddb26f"
    blue: "#6fc2ef"
    magenta: "#e1a3ee"
    cyan: "#12cfc0"
    white: "#f5f5f5"
