colors:
  name: Cloud
  author: ""
  primary:
    background: "#000000"
    foreground: "#ffffff"
  cursor:
    text: "#000000"
    cursor: "#ffffff"
  normal:
    black: "#222827"
    red: "#d5a8e3"
    green: "#9c75dd"
    yellow: "#9898ae"
    blue: "#654a96"
    magenta: "#625566"
    cyan: "#a9d1df"
    white: "#e6ebe5"
  bright:
    black: "#5d6f74"
    red: "#cd749c"
    green: "#63b0b0"
    yellow: "#c0c0dd"
    blue: "#5786bc"
    magenta: "#3f3442"
    cyan: "#849da2"
    white: "#d9d6cf"
