# Colors (Darktooth)
colors:

  # Default colors
  primary:
    background: '#282828'
    foreground: '#fdf4c1'

  # Normal colors
  normal:
    black:   '#282828'
    red:     '#9d0006'
    green:   '#79740e'
    yellow:  '#b57614'
    blue:    '#076678'
    magenta: '#8f3f71'
    cyan:    '#00a7af'
    white:   '#fdf4c1'

  # Bright colors
  bright:
    black:   '#32302f'
    red:     '#fb4933'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#3fd7e5'
    white:   '#ffffc8'

  # Dim colors (Optional)
  dim:
    black:   '#1d2021'
    red:     '#421e1e'
    green:   '#232b0f'
    yellow:  '#4d3b27'
    blue:    '#2b3c44'
    magenta: '#4e3d45'
    cyan:    '#205161'
    white:   '#f4e8ba'
