colors:
  name: Deafened
  author: ""
  primary:
    background: "#000000"
    foreground: "#ffffff"
  cursor:
    text: "#000000"
    cursor: "#ffffff"
  normal:
    black: "#3d3e3d"
    red: "#755a5b"
    green: "#68755a"
    yellow: "#756e5a"
    blue: "#5b6976"
    magenta: "#755b76"
    cyan: "#465457"
    white: "#ccccc6"
  bright:
    black: "#5a5b5c"
    red: "#a37679"
    green: "#87a376"
    yellow: "#a39b76"
    blue: "#758ba3"
    magenta: "#9f76a3"
    cyan: "#899ca1"
    white: "#f8f8f2"
