colors:
  name: Default (dark)
  author: Chris Kempson
  primary:
    background: "#151515"
    foreground: "#d0d0d0"
  cursor:
    text: "#151515"
    cursor: "#d0d0d0"
  normal:
    black: "#151515"
    red: "#ac4142"
    green: "#90a959"
    yellow: "#f4bf75"
    blue: "#6a9fb5"
    magenta: "#aa759f"
    cyan: "#75b5aa"
    white: "#d0d0d0"
  bright:
    black: "#505050"
    red: "#ac4142"
    green: "#90a959"
    yellow: "#f4bf75"
    blue: "#6a9fb5"
    magenta: "#aa759f"
    cyan: "#75b5aa"
    white: "#f5f5f5"
