colors:
  name: Derp
  author: ""
  primary:
    background: "#000000"
    foreground: "#ffffff"
  cursor:
    text: "#000000"
    cursor: "#ffffff"
  normal:
    black: "#111111"
    red: "#d36265"
    green: "#aece91"
    yellow: "#e7e18c"
    blue: "#5297cf"
    magenta: "#963c59"
    cyan: "#5e7175"
    white: "#bebebe"
  bright:
    black: "#666666"
    red: "#ef8171"
    green: "#cfefb3"
    yellow: "#fff796"
    blue: "#74b8ef"
    magenta: "#b85e7b"
    cyan: "#a3babf"
    white: "#ffffff"
