colors:
  name: Digerati
  author: ""
  primary:
    background: "#000000"
    foreground: "#ffffff"
  cursor:
    text: "#000000"
    cursor: "#ffffff"
  normal:
    black: "#303030"
    red: "#c03000"
    green: "#b1d631"
    yellow: "#fecf35"
    blue: "#426870"
    magenta: "#6d506d"
    cyan: "#4bb5c1"
    white: "#e2e2e5"
  bright:
    black: "#5f5f5f"
    red: "#ff3a78"
    green: "#a6cd07"
    yellow: "#b5c865"
    blue: "#4a7781"
    magenta: "#ff3b77"
    cyan: "#4bb5c1"
    white: "#e2e2e5"
