colors:
  name: Dotshare
  author: ""
  primary:
    background: "#000000"
    foreground: "#ffffff"
  cursor:
    text: "#000000"
    cursor: "#ffffff"
  normal:
    black: "#101010"
    red: "#e84f4f"
    green: "#b8d68c"
    yellow: "#e1aa5d"
    blue: "#7dc1cf"
    magenta: "#9b64fb"
    cyan: "#6d878d"
    white: "#dddddd"
  bright:
    black: "#404040"
    red: "#d23d3d"
    green: "#a0cf5d"
    yellow: "#f39d21"
    blue: "#4e9fb1"
    magenta: "#8542ff"
    cyan: "#42717b"
    white: "#dddddd"
