colors:
  name: DWM rob
  author: ""
  primary:
    background: "#000000"
    foreground: "#ffffff"
  cursor:
    text: "#000000"
    cursor: "#ffffff"
  normal:
    black: "#151515"
    red: "#bf7979"
    green: "#97b26b"
    yellow: "#cdcda1"
    blue: "#4a5463"
    magenta: "#9c3885"
    cyan: "#88aadd"
    white: "#ffffff"
  bright:
    black: "#505450"
    red: "#f4a45f"
    green: "#c5f779"
    yellow: "#ffffaf"
    blue: "#7d8794"
    magenta: "#e628ba"
    cyan: "#99ccff"
    white: "#dedede"
