colors:
  name: Eighties (light)
  author: Chris Kempson
  primary:
    background: "#f2f0ec"
    foreground: "#515151"
  cursor:
    text: "#f2f0ec"
    cursor: "#515151"
  normal:
    black: "#2d2d2d"
    red: "#f2777a"
    green: "#99cc99"
    yellow: "#ffcc66"
    blue: "#6699cc"
    magenta: "#cc99cc"
    cyan: "#66cccc"
    white: "#d3d0c8"
  bright:
    black: "#747369"
    red: "#f2777a"
    green: "#99cc99"
    yellow: "#ffcc66"
    blue: "#6699cc"
    magenta: "#cc99cc"
    cyan: "#66cccc"
    white: "#f2f0ec"
