colors:
  name: Embers (light)
  author: Chris Kempson
  primary:
    background: "#dbd6d1"
    foreground: "#433b32"
  cursor:
    text: "#dbd6d1"
    cursor: "#433b32"
  normal:
    black: "#16130f"
    red: "#826d57"
    green: "#57826d"
    yellow: "#6d8257"
    blue: "#6d5782"
    magenta: "#82576d"
    cyan: "#576d82"
    white: "#a39a90"
  bright:
    black: "#5a5047"
    red: "#826d57"
    green: "#57826d"
    yellow: "#6d8257"
    blue: "#6d5782"
    magenta: "#82576d"
    cyan: "#576d82"
    white: "#dbd6d1"
