colors:
  name: Eqie6
  author: ""
  primary:
    background: "#111111"
    foreground: "#cccccc"
  cursor:
    text: "#111111"
    cursor: "#cccccc"
  normal:
    black: "#222222"
    red: "#e84f4f"
    green: "#b7ce42"
    yellow: "#fea63c"
    blue: "#66a9b9"
    magenta: "#b7416e"
    cyan: "#6d878d"
    white: "#cccccc"
  bright:
    black: "#666666"
    red: "#d23d3d"
    green: "#bde077"
    yellow: "#ffe863"
    blue: "#aaccbb"
    magenta: "#e16a98"
    cyan: "#42717b"
    white: "#ffffff"
