colors:
  name: Euphrasia
  author: ""
  primary:
    background: "#cfcfd9"
    foreground: "#1c2027"
  cursor:
    text: "#cfcfd9"
    cursor: "#1c2027"
  normal:
    black: "#192033"
    red: "#a62a3e"
    green: "#38912b"
    yellow: "#b27d12"
    blue: "#355c9a"
    magenta: "#7c4f9f"
    cyan: "#258f8f"
    white: "#77858c"
  bright:
    black: "#666666"
    red: "#f04758"
    green: "#93c724"
    yellow: "#ddb62b"
    blue: "#45a3e6"
    magenta: "#c953ef"
    cyan: "#60c6c8"
    white: "#c0c0c0"
