colors:
  name: GJM
  author: ""
  primary:
    background: "#1c1c1c"
    foreground: "#c5c5c5"
  cursor:
    text: "#1c1c1c"
    cursor: "#c5c5c5"
  normal:
    black: "#1c1c1c"
    red: "#ff005b"
    green: "#cee318"
    yellow: "#ffe755"
    blue: "#048ac7"
    magenta: "#833c9f"
    cyan: "#0ac1cd"
    white: "#e5e5e5"
  bright:
    black: "#666666"
    red: "#ff00a0"
    green: "#ccff00"
    yellow: "#ff9f00"
    blue: "#48c6ff"
    magenta: "#be67e1"
    cyan: "#63e7f0"
    white: "#f3f3f3"
