colors:
  name: Grandshell
  author: ""
  primary:
    background: "#000000"
    foreground: "#bebebe"
  cursor:
    text: "#000000"
    cursor: "#bebebe"
  normal:
    black: "#000000"
    red: "#f25a5a"
    green: "#77bb33"
    yellow: "#efc334"
    blue: "#5555dd"
    magenta: "#c350ff"
    cyan: "#5af2ee"
    white: "#bebebe"
  bright:
    black: "#222222"
    red: "#ffbbbb"
    green: "#dcf692"
    yellow: "#f6df92"
    blue: "#b2baf6"
    magenta: "#f09fff"
    cyan: "#5af2ee"
    white: "#eeeeee"
