colors:
  name: Grayscale (light)
  author: Chris Kempson
  primary:
    background: "#f7f7f7"
    foreground: "#464646"
  cursor:
    text: "#f7f7f7"
    cursor: "#464646"
  normal:
    black: "#101010"
    red: "#7c7c7c"
    green: "#8e8e8e"
    yellow: "#a0a0a0"
    blue: "#686868"
    magenta: "#747474"
    cyan: "#868686"
    white: "#b9b9b9"
  bright:
    black: "#525252"
    red: "#7c7c7c"
    green: "#8e8e8e"
    yellow: "#a0a0a0"
    blue: "#686868"
    magenta: "#747474"
    cyan: "#868686"
    white: "#f7f7f7"
