colors:
  name: Greenscreen (light)
  author: Chris Kempson
  primary:
    background: "#00ff00"
    foreground: "#005500"
  cursor:
    text: "#00ff00"
    cursor: "#005500"
  normal:
    black: "#001100"
    red: "#007700"
    green: "#00bb00"
    yellow: "#007700"
    blue: "#009900"
    magenta: "#00bb00"
    cyan: "#005500"
    white: "#00bb00"
  bright:
    black: "#007700"
    red: "#007700"
    green: "#00bb00"
    yellow: "#007700"
    blue: "#009900"
    magenta: "#00bb00"
    cyan: "#005500"
    white: "#00ff00"
