colors:
  name: hund
  author: hund
  primary:
    background: "#161616"
    foreground: "#FFFFFF"
  cursor:
    text: "#161616"
    cursor: "#FFFFFF"
  normal:
    black: "#222222"
    red: "#E84F4F"
    green: "#B7CE42"
    yellow: "#FEA63C"
    blue: "#66AABB"
    magenta: "#B7416E"
    cyan: "#6D878D"
    white: "#DDDDDD"
  bright:
    black: "#666666"
    red: "#D23D3D"
    green: "#BDE077"
    yellow: "#FFE863"
    blue: "#AACCBB"
    magenta: "#E16A98"
    cyan: "#42717B"
    white: "#CCCCCC"
