# Colors (Iceberg Light)
colors:
  # Default colors
  primary:
    background: '0xe8e9ec'
    foreground: '0x33374c'

  # Normal colors
  normal:
    black:   '0xdcdfe7'
    red:     '0xcc517a'
    green:   '0x668e3d'
    yellow:  '0xc57339'
    blue:    '0x2d539e'
    magenta: '0x7759b4'
    cyan:    '0x3f83a6'
    white:   '0x33374c'

  # Bright colors
  bright:
    black:   '0x8389a3'
    red:     '0xcc3768'
    green:   '0x598030'
    yellow:  '0xb6662d'
    blue:    '0x22478e'
    magenta: '0x6845ad'
    cyan:    '0x327698'
    white:   '0x262a3f'
