colors:
  name: Invisibone
  author: Baskerville
  primary:
    background: "#232323"
    foreground: "#A0A0A0"
  cursor:
    text: "#232323"
    cursor: "#A0A0A0"
  normal:
    black: "#303030"
    red: "#D370A3"
    green: "#6D9E3F"
    yellow: "#B58858"
    blue: "#6095C5"
    magenta: "#AC7BDE"
    cyan: "#3BA275"
    white: "#CFCFCF"
  bright:
    black: "#686868"
    red: "#FFA7DA"
    green: "#A3D572"
    yellow: "#EFBD8B"
    blue: "#98CBFE"
    magenta: "#E5B0FF"
    cyan: "#75DAA9"
    white: "#FFFFFF"
