colors:
  name: Isotope (light)
  author: Chris Kempson
  primary:
    background: "#ffffff"
    foreground: "#606060"
  cursor:
    text: "#ffffff"
    cursor: "#606060"
  normal:
    black: "#000000"
    red: "#ff0000"
    green: "#33ff00"
    yellow: "#ff0099"
    blue: "#0066ff"
    magenta: "#cc00ff"
    cyan: "#00ffff"
    white: "#d0d0d0"
  bright:
    black: "#808080"
    red: "#ff0000"
    green: "#33ff00"
    yellow: "#ff0099"
    blue: "#0066ff"
    magenta: "#cc00ff"
    cyan: "#00ffff"
    white: "#ffffff"
