colors:
  name: Kasugano
  author: Kori Ayakashi
  primary:
    background: "#1b1b1b"
    foreground: "#ffffff"
  cursor:
    text: "#1b1b1b"
    cursor: "#ffffff"
  normal:
    black: "#3D3D3D"
    red: "#6673BF"
    green: "#3EA290"
    yellow: "#B0EAD9"
    blue: "#31658C"
    magenta: "#596196"
    cyan: "#8292B2"
    white: "#C8CACC"
  bright:
    black: "#4D4D4D"
    red: "#899AFF"
    green: "#52AD91"
    yellow: "#98C9BB"
    blue: "#477AB3"
    magenta: "#7882BF"
    cyan: "#95A7CC"
    white: "#EDEFF2"
