colors:
  name: Londontube (dark)
  author: Chris Kempson
  primary:
    background: "#231f20"
    foreground: "#d9d8d8"
  cursor:
    text: "#231f20"
    cursor: "#d9d8d8"
  normal:
    black: "#231f20"
    red: "#ee2e24"
    green: "#00853e"
    yellow: "#ffd204"
    blue: "#009ddc"
    magenta: "#98005d"
    cyan: "#85cebc"
    white: "#d9d8d8"
  bright:
    black: "#737171"
    red: "#ee2e24"
    green: "#00853e"
    yellow: "#ffd204"
    blue: "#009ddc"
    magenta: "#98005d"
    cyan: "#85cebc"
    white: "#ffffff"
