colors:
  name: Marrakesh (dark)
  author: Chris Kempson
  primary:
    background: "#201602"
    foreground: "#948e48"
  cursor:
    text: "#201602"
    cursor: "#948e48"
  normal:
    black: "#201602"
    red: "#c35359"
    green: "#18974e"
    yellow: "#a88339"
    blue: "#477ca1"
    magenta: "#8868b3"
    cyan: "#75a738"
    white: "#948e48"
  bright:
    black: "#6c6823"
    red: "#c35359"
    green: "#18974e"
    yellow: "#a88339"
    blue: "#477ca1"
    magenta: "#8868b3"
    cyan: "#75a738"
    white: "#faf0a5"
