colors:
  name: Material
  author: ""
  primary:
    background: "#263238"
    foreground: "#eceff1"
  cursor:
    text: "#263238"
    cursor: "#eceff1"
  normal:
    black: "#263238"
    red: "#ff9800"
    green: "#8bc34a"
    yellow: "#ffc107"
    blue: "#03a9f4"
    magenta: "#e91e63"
    cyan: "#009688"
    white: "#cfd8dc"
  bright:
    black: "#37474f"
    red: "#ffa74d"
    green: "#9ccc65"
    yellow: "#ffa000"
    blue: "#81d4fa"
    magenta: "#ad1457"
    cyan: "#26a69a"
    white: "#eceff1"
