colors:
  name: Mikado
  author: ""
  primary:
    background: "#000000"
    foreground: "#ffffff"
  cursor:
    text: "#000000"
    cursor: "#ffffff"
  normal:
    black: "#322a2c"
    red: "#a04363"
    green: "#9b9329"
    yellow: "#bf7a29"
    blue: "#6a8c8c"
    magenta: "#856774"
    cyan: "#757978"
    white: "#bcbcaf"
  bright:
    black: "#46423b"
    red: "#ae837a"
    green: "#b4aa30"
    yellow: "#c7a551"
    blue: "#74999e"
    magenta: "#9c818e"
    cyan: "#9fa590"
    white: "#c1c4bc"
