colors:
  name: Mocha (dark)
  author: Chris Kempson
  primary:
    background: "#3b3228"
    foreground: "#d0c8c6"
  cursor:
    text: "#3b3228"
    cursor: "#d0c8c6"
  normal:
    black: "#3b3228"
    red: "#cb6077"
    green: "#beb55b"
    yellow: "#f4bc87"
    blue: "#8ab3b5"
    magenta: "#a89bb9"
    cyan: "#7bbda4"
    white: "#d0c8c6"
  bright:
    black: "#7e705a"
    red: "#cb6077"
    green: "#beb55b"
    yellow: "#f4bc87"
    blue: "#8ab3b5"
    magenta: "#a89bb9"
    cyan: "#7bbda4"
    white: "#f5eeeb"
