colors:
  name: Mono Theme
  author: ""
  primary:
    background: "#000000"
    foreground: "#ffffff"
  cursor:
    text: "#000000"
    cursor: "#ffffff"
  normal:
    black: "#000000"
    red: "#6b6b6b"
    green: "#c4c4c4"
    yellow: "#b3b3b3"
    blue: "#999999"
    magenta: "#717171"
    cyan: "#8a8a8a"
    white: "#b5cabb"
  bright:
    black: "#202020"
    red: "#464646"
    green: "#f8f8f8"
    yellow: "#eeeeee"
    blue: "#7c7c7c"
    magenta: "#adadad"
    cyan: "#c0c0c0"
    white: "#99ac9e"
