colors:
  name: Muse
  author: ""
  primary:
    background: "#000000"
    foreground: "#ffffff"
  cursor:
    text: "#000000"
    cursor: "#ffffff"
  normal:
    black: "#2e3436"
    red: "#a31604"
    green: "#447241"
    yellow: "#c1951a"
    blue: "#425387"
    magenta: "#965d98"
    cyan: "#06989a"
    white: "#d3d7cf"
  bright:
    black: "#555753"
    red: "#c60001"
    green: "#27a343"
    yellow: "#d5a30e"
    blue: "#4a5a8d"
    magenta: "#893c8c"
    cyan: "#12bccb"
    white: "#eeeeec"
