# Colors (New Moon)
colors:
  # Default colors
  primary:
    background: '#2D2D2D'
    foreground: '#B3B9C5'
  # Normal colors
  normal:
    black: '#2D2D2D'
    red: '#F2777A'
    green: '#92D192'
    yellow: '#FFD479'
    blue: '#6AB0F3'
    magenta: '#E1A6F2'
    cyan: '#76D4D6'
    white: '#B3B9C5'
  # Bright colors
  bright:
    black: '#777C85'
    red: '#F2777A'
    green: '#76D4D6'
    yellow: '#FFEEA6'
    blue: '#6AB0F3'
    magenta: '#E1A6F2'
    cyan: '#76D4D6'
    white: '#FFFFFF'
