# Colors (Nightfly)
colors:
   # Default colors
  primary:
     background: '#011627'
     foreground: '#acb4c2'

  cursor:
    text: '#fafafa'
    cursor: '#9ca1aa'

  selection:
    text: '#080808'
    background: '#b2ceee'

   # Normal colors
  normal:
    black:   '#1d3b53'
    red:     '#fc514e'
    green:   '#a1cd5e'
    yellow:  '#e3d18a'
    blue:    '#82aaff'
    magenta: '#c792ea'
    cyan:    '#7fdbca'
    white:   '#a1aab8'

   # Bright colors
  bright:
    black:   '#7c8f8f'
    red:     '#ff5874'
    green:   '#21c7a8'
    yellow:  '#ecc48d'
    blue:    '#82aaff'
    magenta: '#ae81ff'
    cyan:    '#7fdbca'
    white:   '#d6deeb'
