colors: # Default colors
    primary:
      # background: "#2E3440"
      background: "#272d38"
      foreground: "#D8DEE9"

    cursor:
      text: "#BF616A"
      cursor: "#5E81AC"

    # Normal colors
    normal:
      black: "#3B4252"
      red: "#BF616A"
      green: "#A3BE8C"
      yellow: "#EBCB8B"
      blue: "#5E81AC"
      magenta: "#B48EAD"
      cyan: "#88C0D0"
      white: "#E5E9F0"

    # Bright colors
    bright:
      black: "#4C566A"
      red: "#D08770"
      green: "#A3BE8C"
      yellow: "#EBCB8B"
      blue: "#81A1C1"
      magenta: "#B48EAD"
      cyan: "#8FBCBB"
      white: "#ECEFF4"

