colors:
  name: Nudge
  author: ""
  primary:
    background: "#000000"
    foreground: "#ffffff"
  cursor:
    text: "#000000"
    cursor: "#ffffff"
  normal:
    black: "#658280"
    red: "#822f5d"
    green: "#184a31"
    yellow: "#9d4500"
    blue: "#304465"
    magenta: "#330801"
    cyan: "#175552"
    white: "#110005"
  bright:
    black: "#8ca8a6"
    red: "#a24b76"
    green: "#28634d"
    yellow: "#9d5823"
    blue: "#415c77"
    magenta: "#532706"
    cyan: "#3a6868"
    white: "#330801"
