colors:
  name: Orangish
  author: ""
  primary:
    background: "#000000"
    foreground: "#ffffff"
  cursor:
    text: "#000000"
    cursor: "#ffffff"
  normal:
    black: "#251f1f"
    red: "#eb4509"
    green: "#94e76b"
    yellow: "#ffac18"
    blue: "#46aede"
    magenta: "#e32c57"
    cyan: "#d6dbac"
    white: "#efefef"
  bright:
    black: "#5e5e5e"
    red: "#eb4509"
    green: "#95e76b"
    yellow: "#ffac18"
    blue: "#46aede"
    magenta: "#e32c57"
    cyan: "#d6dbac"
    white: "#efefef"
