# Colors (Oxide)
colors:
  # Default colors
  primary:
    background: '#212121'
    foreground: '#c0c5ce'
    bright_foreground: '#f3f4f5'

  cursor:
    text: '#212121'
    cursor: '#c0c5ce'

  # Normal colors
  normal:
    black:   '#212121'
    red:     '#e57373'
    green:   '#a6bc69'
    yellow:  '#fac863'
    blue:    '#6699cc'
    magenta: '#c594c5'
    cyan:    '#5fb3b3'
    white:   '#c0c5ce'

  # Bright colors
  bright:
    black:   '#5c5c5c'
    red:     '#e57373'
    green:   '#a6bc69'
    yellow:  '#fac863'
    blue:    '#6699cc'
    magenta: '#c594c5'
    cyan:    '#5fb3b3'
    white:   '#f3f4f5'
