# Colors (Panda)
colors:
  cursor:
    text: "#fefff2"
    cursor: "#ffb86c"
  selection:
    text: "#e6e6e6"
    background: "#555555"
  primary:
    background: "#292a2b"
    foreground: "#e6e6e6"
  normal:
    black: "#292a2b"
    red: "#ff2c6d"
    green: "#19f9d8"
    yellow: "#ffb86c"
    blue: "#45a9f9"
    magenta: "#ff75b5"
    cyan: "#6fc1ff"
    white: "#e6e6e6"
  bright:
    black: "#555555"
    red: "#ff2c6d"
    green: "#19f9d8"
    yellow: "#ffcc95"
    blue: "#6fc1ff"
    magenta: "#ff9ac1"
    cyan: "#6fc1ff"
    white: "#ffffff"