colors:
  name: Paraiso (dark)
  author: Chris Kempson
  primary:
    background: "#2f1e2e"
    foreground: "#a39e9b"
  cursor:
    text: "#2f1e2e"
    cursor: "#a39e9b"
  normal:
    black: "#2f1e2e"
    red: "#ef6155"
    green: "#48b685"
    yellow: "#fec418"
    blue: "#06b6ef"
    magenta: "#815ba4"
    cyan: "#5bc4bf"
    white: "#a39e9b"
  bright:
    black: "#776e71"
    red: "#ef6155"
    green: "#48b685"
    yellow: "#fec418"
    blue: "#06b6ef"
    magenta: "#815ba4"
    cyan: "#5bc4bf"
    white: "#e7e9db"
