colors:
  name: Phrak1
  author: ""
  primary:
    background: "#000000"
    foreground: "#a8a8a8"
  cursor:
    text: "#000000"
    cursor: "#a8a8a8"
  normal:
    black: "#000000"
    red: "#a80000"
    green: "#00a800"
    yellow: "#a85400"
    blue: "#0000a8"
    magenta: "#a800a8"
    cyan: "#00a8a8"
    white: "#a8a8a8"
  bright:
    black: "#545054"
    red: "#f85450"
    green: "#50fc50"
    yellow: "#f8fc50"
    blue: "#5054f8"
    magenta: "#f854f8"
    cyan: "#50fcf8"
    white: "#f8fcf8"
