colors:
  name: Railscasts (dark)
  author: Chris Kempson
  primary:
    background: "#2b2b2b"
    foreground: "#e6e1dc"
  cursor:
    text: "#2b2b2b"
    cursor: "#e6e1dc"
  normal:
    black: "#2b2b2b"
    red: "#da4939"
    green: "#a5c261"
    yellow: "#ffc66d"
    blue: "#6d9cbe"
    magenta: "#b6b3eb"
    cyan: "#519f50"
    white: "#e6e1dc"
  bright:
    black: "#5a647e"
    red: "#da4939"
    green: "#a5c261"
    yellow: "#ffc66d"
    blue: "#6d9cbe"
    magenta: "#b6b3eb"
    cyan: "#519f50"
    white: "#f9f7f3"
