colors:
  name: Rasi
  author: ""
  primary:
    background: "#000000"
    foreground: "#ffffff"
  cursor:
    text: "#000000"
    cursor: "#ffffff"
  normal:
    black: "#1b1d1e"
    red: "#f92672"
    green: "#82b414"
    yellow: "#fd971f"
    blue: "#4e82aa"
    magenta: "#8c54fe"
    cyan: "#465457"
    white: "#ccccc6"
  bright:
    black: "#505354"
    red: "#ff5995"
    green: "#b6e354"
    yellow: "#feed6c"
    blue: "#0c73c2"
    magenta: "#9e6ffe"
    cyan: "#899ca1"
    white: "#f8f8f2"
