colors:
  name: Rydgel
  author: ""
  primary:
    background: "#000000"
    foreground: "#ffffff"
  cursor:
    text: "#000000"
    cursor: "#ffffff"
  normal:
    black: "#303430"
    red: "#bf7979"
    green: "#97b26b"
    yellow: "#cdcdc1"
    blue: "#86a2be"
    magenta: "#d9b798"
    cyan: "#a1b5cd"
    white: "#ffffff"
  bright:
    black: "#cdb5cd"
    red: "#f4a45f"
    green: "#c5f779"
    yellow: "#ffffed"
    blue: "#98afd9"
    magenta: "#d7d998"
    cyan: "#a1b5cd"
    white: "#dedede"
