colors:
  name: Sex Colors
  author: ""
  primary:
    background: "#000000"
    foreground: "#ffffff"
  cursor:
    text: "#000000"
    cursor: "#ffffff"
  normal:
    black: "#252525"
    red: "#ff9f95"
    green: "#a6e22e"
    yellow: "#fd971f"
    blue: "#435e87"
    magenta: "#789ec6"
    cyan: "#5e7175"
    white: "#dbdcdc"
  bright:
    black: "#454545"
    red: "#ff8d80"
    green: "#b6e354"
    yellow: "#fd971f"
    blue: "#587aa4"
    magenta: "#46a4ff"
    cyan: "#a3babf"
    white: "#fdfdfd"
