colors:
  name: Shapeshifter (dark)
  author: Chris Kempson
  primary:
    background: "#000000"
    foreground: "#ababab"
  cursor:
    text: "#000000"
    cursor: "#ababab"
  normal:
    black: "#000000"
    red: "#e92f2f"
    green: "#0ed839"
    yellow: "#dddd13"
    blue: "#3b48e3"
    magenta: "#f996e2"
    cyan: "#23edda"
    white: "#ababab"
  bright:
    black: "#343434"
    red: "#e92f2f"
    green: "#0ed839"
    yellow: "#dddd13"
    blue: "#3b48e3"
    magenta: "#f996e2"
    cyan: "#23edda"
    white: "#f9f9f9"
