colors:
  name: Shic
  author: ""
  primary:
    background: "#000000"
    foreground: "#ffffff"
  cursor:
    text: "#000000"
    cursor: "#ffffff"
  normal:
    black: "#494949"
    red: "#b9716e"
    green: "#588f7a"
    yellow: "#aaa857"
    blue: "#a0c3c0"
    magenta: "#735e74"
    cyan: "#695935"
    white: "#b1b1b1"
  bright:
    black: "#484848"
    red: "#8f5a58"
    green: "#326f58"
    yellow: "#c7c575"
    blue: "#507f7c"
    magenta: "#a387a6"
    cyan: "#927c4b"
    white: "#c7c7c7"
