# Colors (substrata)
colors:
  primary:
    background: '#191c25'
    foreground: '#b5b4c9'
  normal:
    black:   '#2e313d'
    red:     '#cf8164'
    green:   '#76a065'
    yellow:  '#ab924c'
    blue:    '#8296b0'
    magenta: '#a18daf'
    cyan:    '#659ea2'
    white:   '#b5b4c9'
  bright:
    black:   '#5b5f71'
    red:     '#fe9f7c'
    green:   '#92c47e'
    yellow:  '#d2b45f'
    blue:    '#a0b9d8'
    magenta: '#c6aed7'
    cyan:    '#7dc2c7'
    white:   '#f0ecfe'


