colors:
  name: Swayr
  author: ""
  primary:
    background: "#1c1709"
    foreground: "#c2b9a1"
  cursor:
    text: "#1c1709"
    cursor: "#c2b9a1"
  normal:
    black: "#1c1709"
    red: "#8e4317"
    green: "#787200"
    yellow: "#945c00"
    blue: "#315094"
    magenta: "#5c2e40"
    cyan: "#00617d"
    white: "#c2b9a1"
  bright:
    black: "#4f4939"
    red: "#f07935"
    green: "#d9d138"
    yellow: "#ffab26"
    blue: "#8aa9ed"
    magenta: "#ff8cb8"
    cyan: "#43bfe0"
    white: "#f2e8c9"
