colors:
  name: Sweet Love
  author: Boroshlawa
  primary:
    background: "#1F1F1F"
    foreground: "#C0B18B"
  cursor:
    text: "#1F1F1F"
    cursor: "#C0B18B"
  normal:
    black: "#4A3637"
    red: "#D17B49"
    green: "#7B8748"
    yellow: "#AF865A"
    blue: "#535C5C"
    magenta: "#775759"
    cyan: "#6D715E"
    white: "#C0B18B"
  bright:
    black: "#402E2E"
    red: "#AC5D2F"
    green: "#647035"
    yellow: "#8F6840"
    blue: "#444B4B"
    magenta: "#614445"
    cyan: "#585C49"
    white: "#978965"
