colors:
  name: theme2
  author: ""
  primary:
    background: "#000000"
    foreground: "#ffffff"
  cursor:
    text: "#000000"
    cursor: "#ffffff"
  normal:
    black: "#191919"
    red: "#eb3d51"
    green: "#66b61a"
    yellow: "#d98e1d"
    blue: "#23ffa8"
    magenta: "#ff00da"
    cyan: "#68a783"
    white: "#eaeaea"
  bright:
    black: "#484848"
    red: "#be6262"
    green: "#4b8a10"
    yellow: "#e5d95e"
    blue: "#23aaff"
    magenta: "#ab005b"
    cyan: "#bbcd81"
    white: "#bbbbbb"
