colors:
  name: thwump
  author: ""
  primary:
    background: "#000000"
    foreground: "#ffffff"
  cursor:
    text: "#000000"
    cursor: "#ffffff"
  normal:
    black: "#202020"
    red: "#a07070"
    green: "#70a070"
    yellow: "#a0a070"
    blue: "#7070a0"
    magenta: "#a070a0"
    cyan: "#70a0a0"
    white: "#a0a0a0"
  bright:
    black: "#505050"
    red: "#d07070"
    green: "#70d070"
    yellow: "#d0d070"
    blue: "#7070d0"
    magenta: "#d070d0"
    cyan: "#70d0d0"
    white: "#f0f0f0"
