colors:
  name: Tomorrow (light)
  author: Chris Kempson
  primary:
    background: "#ffffff"
    foreground: "#373b41"
  cursor:
    text: "#ffffff"
    cursor: "#373b41"
  normal:
    black: "#1d1f21"
    red: "#cc6666"
    green: "#b5bd68"
    yellow: "#f0c674"
    blue: "#81a2be"
    magenta: "#b294bb"
    cyan: "#8abeb7"
    white: "#c5c8c6"
  bright:
    black: "#969896"
    red: "#cc6666"
    green: "#b5bd68"
    yellow: "#f0c674"
    blue: "#81a2be"
    magenta: "#b294bb"
    cyan: "#8abeb7"
    white: "#ffffff"
