colors:
  name: Twilight (dark)
  author: Chris Kempson
  primary:
    background: "#1e1e1e"
    foreground: "#a7a7a7"
  cursor:
    text: "#1e1e1e"
    cursor: "#a7a7a7"
  normal:
    black: "#1e1e1e"
    red: "#cf6a4c"
    green: "#8f9d6a"
    yellow: "#f9ee98"
    blue: "#7587a6"
    magenta: "#9b859d"
    cyan: "#afc4db"
    white: "#a7a7a7"
  bright:
    black: "#5f5a60"
    red: "#cf6a4c"
    green: "#8f9d6a"
    yellow: "#f9ee98"
    blue: "#7587a6"
    magenta: "#9b859d"
    cyan: "#afc4db"
    white: "#ffffff"
