colors:
  name: Vacuous 2
  author: hal
  primary:
    background: "#101010"
    foreground: "#d2c5bc"
  cursor:
    text: "#101010"
    cursor: "#d2c5bc"
  normal:
    black: "#202020"
    red: "#b91e2e"
    green: "#81957c"
    yellow: "#f9bb80"
    blue: "#356579"
    magenta: "#2d2031"
    cyan: "#0b3452"
    white: "#909090"
  bright:
    black: "#606060"
    red: "#d14548"
    green: "#a7b79a"
    yellow: "#fae3a0"
    blue: "#7491a1"
    magenta: "#87314e"
    cyan: "#0f829d"
    white: "#fff0f0"
