colors:
  name: VisiBlue
  author: ""
  primary:
    background: "#000000"
    foreground: "#666699"
  cursor:
    text: "#000000"
    cursor: "#666699"
  normal:
    black: "#333366"
    red: "#6666cc"
    green: "#0099cc"
    yellow: "#3366cc"
    blue: "#006699"
    magenta: "#0066ff"
    cyan: "#669999"
    white: "#99cccc"
  bright:
    black: "#333399"
    red: "#9999ff"
    green: "#00ccff"
    yellow: "#6699ff"
    blue: "#0099cc"
    magenta: "#0099ff"
    cyan: "#66cccc"
    white: "#ccffff"
