#!/usr/bin/env bash

ln -s ~/Dotfiles/nordfiles/config/alacritty ~/.config &
ln -s ~/Dotfiles/nordfiles/config/BetterDiscord/themes  ~/.config/BetterDiscord/ &
ln -s ~/Dotfiles/nordfiles/config/bpython ~/.config &
ln -s ~/Dotfiles/nordfiles/config/bpytop ~/.config &
ln -s ~/Dotfiles/nordfiles/config/bspwm ~/.config &
ln -s ~/Dotfiles/nordfiles/config/cava ~/.config &
ln -s ~/Dotfiles/nordfiles/config/dunst ~/.config &
ln -s ~/Dotfiles/nordfiles/config/eww ~/.config &
ln -s ~/Dotfiles/nordfiles/config/fish/config.fish ~/.config/fish &
ln -s ~/Dotfiles/nordfiles/config/flameshot ~/.config &
ln -s ~/Dotfiles/nordfiles/config/fontconfig ~/.config &
ln -s ~/Dotfiles/nordfiles/config/GIMP/2.10/splashes ~/.config/GIMP/2.10/ &
ln -s ~/Dotfiles/nordfiles/config/gtk-2.0 ~/.config/ &
ln -s ~/Dotfiles/nordfiles/config/gtk-3.0 ~/.config/ &
ln -s ~/Dotfiles/nordfiles/config/kitty ~/.config/ &
ln -s ~/Dotfiles/nordfiles/config/komorebi ~/.config/ &
ln -s ~/Dotfiles/nordfiles/config/mpd ~/.config/ &
ln -s ~/Dotfiles/nordfiles/config/mpv ~/.config/ &
ln -s ~/Dotfiles/nordfiles/config/ncmpcpp ~/.config/ &
ln -s ~/Dotfiles/nordfiles/config/neofetch ~/.config/ &
ln -s ~/Dotfiles/nordfiles/config/nvim/lua/custom ~/.config/nvim/lua &
ln -s ~/Dotfiles/nordfiles/config/nvim/lua/plugins/ ~/.config/nvim/lua &
ln -s ~/Dotfiles/nordfiles/config/omf ~/.config &
ln -s ~/Dotfiles/nordfiles/config/picom ~/.config &
ln -s ~/Dotfiles/nordfiles/config/polybar ~/.config &
ln -s ~/Dotfiles/nordfiles/config/qBittorrent/themes ~/.config/qBittorrent &
ln -s ~/Dotfiles/nordfiles/config/qutebrowser ~/.config &
ln -s ~/Dotfiles/nordfiles/config/ranger ~/.config &
ln -s ~/Dotfiles/nordfiles/config/redshift ~/.config &
ln -s ~/Dotfiles/nordfiles/config/rofi ~/.config &
ln -s ~/Dotfiles/nordfiles/config/spicetify/config-xpui.ini ~/.config/spicetify &
ln -s ~/Dotfiles/nordfiles/config/sxhkd ~/.config/sxhkd &
ln -s ~/Dotfiles/nordfiles/config/tilda ~/.config &
ln -s ~/Dotfiles/nordfiles/config/wal ~/.config &
ln -s ~/Dotfiles/nordfiles/config/zathura ~/.config &
ln -s ~/Dotfiles/nordfiles/config/.tmux.conf ~/.config &
ln -s ~/Dotfiles/nordfiles/config/betterlockscreenrc ~/.config &
ln -s ~/Dotfiles/nordfiles/config/mimeapps.list ~/.config  &
ln -s ~/Dotfiles/nordfiles/config/screenkey.json ~/.config &

ln -s ~/Dotfiles/nordfiles/home/.icons ~ &
ln -s ~/Dotfiles/nordfiles/home/.urxvt ~ &
ln -s ~/Dotfiles/nordfiles/home/.bashrc ~ &
ln -s ~/Dotfiles/nordfiles/home/.fehbg ~ &
ln -s ~/Dotfiles/nordfiles/home/.gtkrc-2.0 ~ &
ln -s ~/Dotfiles/nordfiles/home/.p10k.zsh ~ &
ln -s ~/Dotfiles/nordfiles/home/.profile ~ &
ln -s ~/Dotfiles/nordfiles/home/.xinitrc ~ &
ln -s ~/Dotfiles/nordfiles/home/.Xresources ~ &
ln -s ~/Dotfiles/nordfiles/home/.zshenv ~ &
ln -s ~/Dotfiles/nordfiles/home/.zshrc ~ &
