# Shell variables
# Generated by 'wal'
wallpaper='/home/maker/Pictures/wallpapers/nord/covers.png'

# Special
background='#3b4252'
foreground='#d8dee9'
cursor='#81a1c1'

# Colors
color0='#3B4252'
color8='#434C5E'
color1='#BF616A'
color9='#D08770'
color2='#A3BE8C'
color10='#A3BE8C'
color3='#EBCB8B'
color11='#EBCB8B'
color4='#5E81AC'
color12='#81A1C1'
color5='#B48EAD'
color13='#B48EAD'
color6='#88C0D0'
color14='#8FBCBB'
color7='#E5E9F0'
color15='#ECEFF4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:12,fg+:232,bg+:12,hl+:255
    --color info:7,prompt:12,spinner:12,pointer:1,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
