# Shell variables
# Generated by 'wal'
wallpaper='/home/maker/Pictures/wallpapers/onedark/BirdOneDark.png'

# Special
background='#1e222a'
foreground='#ABB2BF'
cursor='#61AFEF'

# Colors
color0='#1E2127'
color1='#E06C75'
color2='#98C379'
color3='#D19A66'
color4='#61AFEF'
color5='#C678DD'
color6='#56B6C2'
color7='#ABB2BF'
color8='#5C6370'
color9='#E06C75'
color10='#98C379'
color11='#e5c07b'
color12='#61BFEF'
color13='#C678DD'
color14='#56B6C2'
color15='#FFFFFF'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
