default_keybindings = false
use_nerdfont = true
notify = true
gapless = true
flip_status_indicators = true
shuffle = false
repeat = 'playlist'
cover_max_scale = 2

[keybindings]
"b" = "seek -1000"
"f" = "seek +1000"
"B" = "seek -10000"
"F" = "seek +10000"
"p" = "playpause"
"Enter" = "play"
"s" = "stop"
"H" = "previous"
"L" = "next"
"r" = "repeat"
"z" = "shuffle"
"D" = "delete"
"S" = "save"
"O" = "open current"
"o" = "open selected"
"A" = "goto artist"
"a" = "goto album"
" " = "queue"
"Ctrl+s" = "save queue"
"J" = "shift down 1"
"K" = "shift up 1"
"C" = "clear"
"Ctrl+v" = "insert"
"=" = "volup 1"
"-" = "voldown 1"
"[" = "volup 5"
"]" = "voldown 5"
"F1" = "focus queue"
"F2" = "focus library"
"F3" = "focus search"
"1" = "focus queue"
"2" = "focus library"
"." = "move playing"
"Down" = "move down 1"
"G" = "move bottom"
"g" = "move top"
"Left" = "move left 1"
"Right" = "move right 1"
"Ctrl+d" = "move down 5"
"Ctrl+u" = "move up 5"
"Up" = "move up 1"
"h" = "move left 1"
"j" = "move down 1"
"k" = "move up 1"
"Ctrl+e" = "move down 1"
"Ctrl+y" = "move up 1"
"l" = "move right 1"
"." = "move playing"
"q" = "back"
"t" = "sort added d"
"T" = "sort title a"
"Y" = "share selected"
"y" = "share current"
"Q" = "quit"
"Z" = "quit"
"?" = "help"
"U" = "update"

[track_format]
left = "%artists - %title"
center = "%album"
right = "%saved %duration"

[theme]
background = ""
primary = "white"
secondary = "light black"
title = "green"
playing = "green"
playing_bg = "black"
highlight = "black"
highlight_bg = "blue"
error = "light white"
error_bg = "red"
statusbar = "black"
statusbar_progress = "light green"
statusbar_bg = "green"
cmdline = "light white"
cmdline_bg = ""

# vim: ft=cfg
