-- This file has been generated by regen.py
-- Changes may be overwritten the next time 
-- configs are re-generated

local N = {}

N.common = {
  ["base00"] = "%(base00)s",
  ["base01"] = "%(base01)s",
  ["base02"] = "%(base02)s",
  ["base03"] = "%(base03)s",

  ["base04"] = "%(base04)s",
  ["base05"] = "%(base05)s",
  ["base06"] = "%(base06)s",

  ["base07"] = "%(base07)s",
  ["base08"] = "%(base08)s",
  ["base09"] = "%(base09)s",
  ["base10"] = "%(base10)s",

  ["base11"] = "%(base11)s",
  ["base12"] = "%(base12)s",
  ["base13"] = "%(base13)s",
  ["base14"] = "%(base14)s",
  ["base15"] = "%(base15)s",
}

N.shades = {
  ["shade00"] = "%(shade00)s",
  ["shade01"] = "%(shade01)s",
  ["shade02"] = "%(shade02)s",
  ["shade03"] = "%(shade03)s",
  ["shade04"] = "%(shade04)s",
  ["shade05"] = "%(shade05)s",
  ["shade06"] = "%(shade06)s",
  ["shade07"] = "%(shade07)s",
  ["shade08"] = "%(shade08)s",
  ["shade09"] = "%(shade09)s",
  ["shade10"] = "%(shade10)s",
  ["shade11"] = "%(shade11)s",
  ["shade12"] = "%(shade12)s",
}

N.rainbow = {
  ["cobalt"] = "%(cobalt)s",
  ["pink"] = "%(pink)s",
  ["cyan"] = "%(cyan)s",
  ["green"] = "%(green)s",
  ["yellow"] = "%(yellow)s",
  ["orange"] = "%(orange)s",
  ["purple"] = "%(purple)s",
}

N.modes = setmetatable({
  ["n"] = "%(base14)s",
  ["no"] = "%(base08)s",
  ["v"] = "%(base09)s",
  ["V"] = "%(color05)s",
  [""] = "%(color00)s",
  ["s"] = "%(base15)s",
  ["S"] = "%(base10)s",
  [""] = "%(base11)s ",
  ["i"] = "%(base07)s",
  ["ic"] = "%(color19)s",
  ["R"] = "%(color08)s",
  ["Rv"] = "%(color10)s",
  ["c"] = "%(color09)s",
  ["cv"] = "%(base12)s",
  ["ce"] = "%(base12)s",
  ["r"] = "%(color19)s",
  ["rm"] = "%(color17)s",
  ["r?"] = "%(color04)s",
  ["t"] = "%(color06)s",
}, {
  __index = function()
    return "%(color06)s"
  end,
})

N.syntax = {
  ["color16"] = "%(color16)s",
  ["color09"] = "%(color09)s",

  ["color00"] = "%(color00)s",
  ["color03"] = "%(color03)s",
  ["color02"] = "%(color02)s",
  ["color19"] = "%(color19)s",

  ["color17"] = "%(color17)s",
  ["color20"] = "%(color20)s",

  ["color13"] = "%(color13)s",
  ["color01"] = "%(color01)s",
  ["color05"] = "%(color05)s",

  ["color12"] = "%(color12)s",
  ["color15"] = "%(color15)s",
  ["color04"] = "%(color04)s",

  ["color06"] = "%(color06)s",
  ["color08"] = "%(color08)s",

  ["color10"] = "%(color10)s",
  ["color11"] = "%(color11)s",

  ["color18"] = "%(color18)s",
  ["color14"] = "%(color14)s",
  ["color07"] = "%(color07)s",
}

return N

-- vim:ft=lua
