-- This file has been generated by regen.py
-- Changes may be overwritten the next time 
-- configs are re-generated

return {
    color_foreground = "%(base05)s",
    color_background = "%(base00)s",
    color_window_background = "%(base00)s",
    color_bold = "%(base05)s",
    color_cursor = '%(base09)s',
    color_cursor_foreground = "%(base00)s",
    color_highlight = "%(base05)s",
    color_highlight_foreground = "%(base05)s",
    color_0 = '%(base01)s',
    color_1 = '%(base11)s',
    color_2 = '%(base14)s',
    color_3 = '%(base13)s',
    color_4 = '%(base09)s',
    color_5 = '%(base15)s',
    color_6 = '%(base08)s',
    color_7 = '%(base05)s',
    color_8 = '%(base04)s',
    color_9 = '%(base11)s',
    color_10 = '%(base12)s',
    color_11 = '%(base13)s',
    color_12 = '%(base09)s',
    color_13 = '%(base10)s',
    color_14 = '%(base07)s',
    color_15 = '%(base06)s'
}

-- vim:filetype=lua
