#!/usr/bin/env bash

export XDG_CURRENT_DESKTOP="bspwm"

source "$XDG_CONFIG_HOME/bspwm/defaults.bash"
source "$XDG_CONFIG_HOME/bspwm/exports.bash"
source "$XDG_CONFIG_HOME/bspwm/launcher.bash"

# vim:ft=bash:nowrap
