#!/usr/bin/env bash

export XDG_CURRENT_DESKTOP="bspwm"

$XDG_CONFIG_HOME/bspwm/defaults.bash &
$XDG_CONFIG_HOME/bspwm/exports.bash &
$XDG_CONFIG_HOME/bspwm/launcher.bash &
exit 0

# vim:ft=bash:nowrap
