#!/usr/bin/env sh

handle_image() {
  case "$1" in
    image/jpeg|image/png) jp2a --colors "$2" ;;
    *) file --no-pad --dereference "$2" ;;
  esac
}

handle_text() {
  case "$2" in
    *.md) glow --style=auto "$2" ;;
    *.htm|*.html) pandoc --standalone --to=markdown "$2" ;;
    *) bat --theme=base16 --color=always --paging=never --number --italic-text=never --tabs=2 --wrap=never "$2" ;;
  esac
}

mime="$(file --brief --mime-type "$1")"
case "$mime" in
  text/*) handle_text "$mime" "$1" ;;
  inode/directory) exa --long --icons --color=always "$1" ;;
  application/json) jq --color-output < "$1" ;;
  application/x-bittorrent) transmission-show --unsorted "$1" ;;
  image/*) handle_image "$mime" "$1" ;;
  *) file --no-pad --dereference "$1" ;;
esac
