## This file has been generated by regen.py
## Changes may be overwritten the next time 
## configs are re-generated

# Colors
# black
export foreground='#d4d4d5'
export background='#101317'

export base00='#171C21'
export base08='#949494'

# red
export base01='#f87070'
export base09='#f87070'

# green
export base02='#79dcaa'
export base10='#36c692'

# yellow
export base03='#ffe59e'
export base11='#ffe59e'
 
# blue
export base04='#7ab0df'
export base12='#7ab0df'

# magenta
export base05='#c397d8'
export base13='#b77ee0'

# cyan
export base06='#70c0ba'
export base14='#54ced6'

# white
export base07='#d4d4d5'
export base15='#ffffff'

# vim:filetype=zsh
