#!/bin/env bash

SAVEPATH=$XDG_PICTURES_DIR/$(date).png
case "$1" in 
    --selected)
        maim --select "$SAVEPATH" &
        wait
        dunstify -u normal -i "$SAVEPATH" "Screenshot Saved" "Your screenshot has been saved to $SAVEPATH"
        ;;
    --fullscreen)
        maim "$SAVEPATH" &
        wait
        dunstify -u normal -i "$SAVEPATH" "Screenshot Saved" "Your screenshot has been saved to $SAVEPATH"
        ;;
    *)
        echo "No such option!"
        ;;
esac
