-- This file has been generated by regen.py
-- Changes may be overwritten the next time 
-- configs are re-generated

return {
    color_foreground = "#d4d4d5",
    color_background = "#101317",
    color_window_background = "#101317",
    color_bold = "#d4d4d5",
    color_cursor = '#7ab0df',
    color_cursor_foreground = "#101317",
    color_highlight = "#d4d4d5",
    color_highlight_foreground = "#d4d4d5",
    color_0 = '#171C21',
    color_1 = '#f87070',
    color_2 = '#79dcaa',
    color_3 = '#ffe59e',
    color_4 = '#7ab0df',
    color_5 = '#c397d8',
    color_6 = '#70c0ba',
    color_7 = '#d4d4d5',
    color_8 = '#949494',
    color_9 = '#f87070',
    color_10 = '#36c692',
    color_11 = '#ffe59e',
    color_12 = '#7ab0df',
    color_13 = '#b77ee0',
    color_14 = '#54ced6',
    color_15 = '#ffffff'
}

-- vim:filetype=lua
