-- This file has been generated by regen.py
-- Changes may be overwritten the next time 
-- configs are re-generated

return {
    color_foreground = "#BEBEBE",
    color_background = "#151A1F",
    color_window_background = "#151A1F",
    color_bold = "#BEBEBE",
    color_cursor = '#c9938a',
    color_cursor_foreground = "#151A1F",
    color_highlight = "#BEBEBE",
    color_highlight_foreground = "#BEBEBE",
    color_0 = '#2C3035',
    color_1 = '#8AAC8B',
    color_2 = '#948FB1',
    color_3 = '#7797B7',
    color_4 = '#c9938a',
    color_5 = '#AC8A8C',
    color_6 = '#AC8A8C',
    color_7 = '#BEBEBE',
    color_8 = '#42484E',
    color_9 = '#8AAC8B',
    color_10 = '#8AABAC',
    color_11 = '#7797B7',
    color_12 = '#c9938a',
    color_13 = '#ACA98A',
    color_14 = '#B0B0B0',
    color_15 = '#BBBBBB'
}

-- vim:filetype=lua
