#!/bin/sh

USERNAME="$1"
LOCKSCREEN_WALL="/home/$USERNAME/Pictures/walls/radium/output-1659958136.png"
RESOLUTION="$(xdpyinfo | grep dimensions | awk '{print $2}')"
DEFAULT_DPMS=$(xset q | awk '/^[[:blank:]]*DPMS is/ {print $(NF)}')
LOCK_TIMEOUT=5 ### In Seconds

foreground="$(xrdb -query | grep 'foreground:' | awk '{print $NF}')"
background="$(xrdb -query | grep 'background:' | awk '{print $NF}')"
black="$(xrdb -query | grep 'color0:' | awk '{print $NF}')"
red="$(xrdb -query | grep 'color1:' | awk '{print $NF}')"
green="$(xrdb -query | grep 'color2:' | awk '{print $NF}')"
yellow="$(xrdb -query | grep 'color3:' | awk '{print $NF}')"
blue="$(xrdb -query | grep 'color4:' | awk '{print $NF}')"
magenta="$(xrdb -query | grep 'color5:' | awk '{print $NF}')"
cyan="$(xrdb -query | grep 'color6:' | awk '{print $NF}')"
white="$(xrdb -query | grep 'color7:' | awk '{print $NF}')"
grey="$(xrdb -query | grep 'color8:' | awk '{print $NF}')"
shade="$(xrdb -query | grep 'shade07:' | awk '{print $NF}')"

lock() {
  convert "$LOCKSCREEN_WALL" -resize "$RESOLUTION" RGB:- | i3lock \
    --raw "$RESOLUTION:rgb"         \
    --image /dev/stdin              \
    --nofork                        \
    --beep                          \
    --fill                          \
    --force-clock                   \
    --ignore-empty-password         \
    --show-failed-attempts          \
    --pass-media-keys               \
    --pass-screen-keys              \
    --pass-power-keys               \
    --pass-volume-keys              \
    --pointer=default               \
    --screen=0                      \
    --radius=25                     \
    --ring-width=20                 \
    --color='#00000000'             \
    --insidewrong-color='#00000000' \
    --inside-color='#00000000'      \
    --insidever-color='#00000000'   \
    --ring-color="$red"             \
    --ringver-color="$green"        \
    --ringwrong-color="$red"        \
    --keyhl-color="$cyan"           \
    --separator-color="$yellow"     \
    --verif-color="$green"          \
    --wrong-color="$blue"           \
    --modif-color="$magenta"        \
    --time-color="$blue"            \
    --date-color="$red"             \
    --greeter-color="$cyan"         \
    --timeoutline-color="$magenta"  \
    --time-str=%H:%M                \
    --date-str='%A, %e %B'          \
    --verif-text=''                 \
    --wrong-text=''                 \
    --noinput-text=''               \
    --lock-text=''                  \
    --lockfailed-text=''            \
    --greeter-text="Hello, $USER."  \
    --time-align=1                  \
    --date-align=1                  \
    --verif-align=2                 \
    --wrong-align=2                 \
    --modif-align=2                 \
    --greeter-align=2               \
    --timeoutline-width=5           \
    --time-size=300                 \
    --date-size=50                  \
    --date-font=Caviar\ Dreams      \
    --verif-font=Caviar\ Dreams     \
    --wrong-font=Caviar\ Dreams     \
    --greeter-font=Caviar\ Dreams   \
    --time-font=Koulen              \
    --time-pos=100:850              \
    --date-pos=105:910              \
    --greeter-pos=275:150           \
    --ind-pos=1800:130
}

[ "$DEFAULT_DPMS" = Enabled ] && xset dpms "$LOCK_TIMEOUT"
lock
[ "$DEFAULT_DPMS" = Enabled ] && xset dpms 0
