window:
  padding:
   x: 15
   y: 10

  dynamic_padding: true
  decorations: none
  opacity: 1.0

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: Iosevka Nerd Font
    style: Regular
  bold:
    family: Iosevka Nerd Font
    style: Bold
  italic:
    family: Iosevka Nerd Font
    style: Italic
  bold_italic:
    family: Iosevka Nerd Font
    style: Bold Italic

  size: 14.4

  offset:
   x: 0
   y: 5

  glyph_offset:
   x: 0
   y: 3

  builtin_box_drawing: true

draw_bold_text_with_bright_colors: true

colors:
  primary:
    background: '#101317'
    foreground: '#D4D4D5'
  cursor:
    text:   CellForeground
    cursor: '#7AB0DF'
  bright:
    black:   "#171C21"
    red:     "#fa6969"
    green:   "#36C692"
    yellow:  "#FFCE66"
    blue:    "#7AB0DF"
    magenta: "#B77EE0"
    cyan:    "#54CED6"
  normal:
    black:   "#171C21"
    red:     "#F87070"
    green:   "#79DCAA"
    yellow:  "#FFE59E"
    blue:    "#7AB0DF"
    magenta: "#C397D8"
    cyan:    "#70C0BA"
    white:   "#D4D4D5"
    white:   "#FFFFFF"

live_config_reload: true

shell:
 program: /usr/bin/zsh
