#!/bin/sh

# Monitor settings
pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5

# Window settings
bspc config border_width         3
bspc config window_gap           8
bspc config top_padding 	     0

bspc config focused_border_color "#4c566a"
bspc config normal_border_color "#4c566a"
bspc config presel_border_color "#8F3724"
bspc config urgent_border_color "#504339"
bspc config focused_private_border_color "#35BF5C"

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false

# Program settings 
bspc rule -a Screenkey --unmanage
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a mpv state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a spotify='^5' 
bspc rule -a spotify state=pseudo_tiled
bspc rule -a TelegramDesktop desktop='^4'
bspc rule -a Firefox desktop='^2'
bspc rule -a Zathura state=tiled 
bspc rule -a conky sticky=off manage=off lower=on
bspc rule -a lxappearance state=floating center=true
bspc rule -a tilda state=floating center=true border=off sticky=on
bspc rule -a Tilda state=floating center=true border=off sticky=on
bspc rule -a feh state=floating floating=true manage=on center=true

/home/maker/.config/bspwm/exports &
/home/maker/.config/bspwm/launcher &
exit

