#!/usr/bin/env zsh

gtktheme () {
    while IFS='=' read -r key value; do
        if [ "${key}" = "gtk-theme-name" ]; then
            printf '%s' "${value}"
            return 0
        fi
    done < "$XDG_CONFIG_HOME/gtk-3.0/settings.ini"
}

old=$(cat $XDG_CACHE_HOME/jgmenu/.last-gtktheme)
new=$(gtktheme)

if ! [ "${old}" = "${new}" ]; then
    printf '%b
' "info: change gtk theme from ${old} to ${new}"
    jgmenu_run gtktheme
fi

