#!/usr/bin/env bash

## Files and cmd
FILE="$HOME/.cache/eww_launch_main.xyz"

## Run eww daemon if not running already
if [[ ! "$(pidof eww)" ]]; then
	eww daemon
	sleep 1
fi

## Open widgets 
run_eww() {
	eww open-many "background"    	 \
					 "time" 	     					 \
					 "user"		               \
					 "system" 	     				 \
					 "uptime"        				 \
					 "directories"   				 \
					 "wshutdown"     				 \
					 "wreboot"       				 \
					 "wlogout"       				 \
					 "wlock"	     					 \
					 "wsuspend"       			 \
					 "mpd"		 						   \
					 "quicklinks"						 \
					 "audiocontrol"
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww
else
	eww close "background"    	 		 \
					 "time" 	     					 \
					 "user"		               \
					 "system" 	     				 \
					 "uptime"        				 \
					 "directories"   				 \
					 "wshutdown"     				 \
					 "wreboot"       				 \
					 "wlogout"       				 \
					 "wlock"	     					 \
					 "wsuspend"       			 \
					 "mpd"		 						 	 \
					 "quicklinks"						 \
					 "audiocontrol"
	rm "$FILE"
fi
