#!/usr/bin/env bash

## Files and cmd
FILE="$HOME/.cache/eww_launch.xyz"
EWW="$HOME/.bin/eww"

## Run eww daemon if not running already
if [[ ! "$(pidof eww)" ]]; then
	${EWW} daemon
	sleep 1
fi

## Open widgets 
run_eww() {
	${EWW} open-many "background"    \
					 "time" 	     					 \
					 "user"		               \
					 "system" 	     				 \
					 "uptime"        				 \
					 "wmanganelo"    				 \
					 "directories"   				 \
					 "wshutdown"     				 \
					 "wreboot"       				 \
					 "wlogout"       				 \
					 "wlock"	     					 \
					 "wsuspend"       			 \
					 "audio"		 						 \
					 "quicklinks"						 \
					 "audiocontrol"
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww
else
	${EWW} close-all
	rm "$FILE"
fi
